spring:
  profiles:
    active: dev
  ai: # need fix
    google:
      genai:
        api-key: # need add\
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

springdoc:
  packages-to-scan: com.ohgiraffers.hw22thteamproject
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: method # operations 정렬 방식은 HTTP Method 순
    tags-sorter: alpha # tag 정렬 방식은 알파벳 순
    path: "swagger.html" # http://localhost:8080/swagger.html로 접속 가능
